services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
  redis:
    image: redis:7.4-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - REDIS_ADDRESS=redis:6379
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    entrypoint: ["/app/wait-for-it.sh","postgres:5432","--","/app/start.sh"]
    command: ["/app/main"]
volumes:
  data-volume:

